ci:
  collect:
    numberOfRuns: 5
    settings:
      preset: desktop
      onlyCategories:
        - performance
      chromeFlags: --disable-dev-shm-usage
      skipAudits:
        - bootup-time
        - critical-request-chains
        - cumulative-layout-shift
        - diagnostics
        - dom-size
        - duplicated-javascript
        - efficient-animated-content
        - final-screenshot
        - first-contentful-paint
        - first-meaningful-paint
        - font-display
        - full-page-screenshot
        - interactive
        - largest-contentful-paint
        - largest-contentful-paint-element
        - layout-shift-elements
        - legacy-javascript
        - long-tasks
        - main-thread-tasks
        - mainthread-work-breakdown
        - max-potential-fid
        - modern-image-formats
        - network-requests
        - network-rtt
        - network-server-latency
        - no-document-write
        - non-composited-animations
        - offscreen-images
        - performance-budget
        - preload-lcp-image
        - redirects
        - render-blocking-resources
        - resource-summary
        - screenshot-thumbnails
        - script-treemap-data
        - speed-index
        - third-party-facades
        - third-party-summary
        - timing-budget
        - total-blocking-time
        - total-byte-weight
        - unminified-css
        - unminified-javascript
        - unsized-images
        - unused-css-rules
        - unused-javascript
        - user-timings
        - uses-http2
        - uses-long-cache-ttl
        - uses-optimized-images
        - uses-passive-event-listeners
        - uses-rel-preconnect
        - uses-rel-preload
        - uses-responsive-images
        - uses-text-compression
